version: '3'
services:
        paneldash:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: mydash/latest
                ports:
                        - "4343:8080"